### ISSUE TITLE
Use PUB_HOSTED_URL for hosted packages

### ISSUE THREAD

**Issue by itsjoeconway** [dart-lang/pub_cache#34]
Currently, users in China get packages from a mirror. They must set their PUB_HOSTED_URL to https://flutter-io.cn. This package hardcores PUB_HOSTED_URL to pub.dartlang.org. 

I'm happy to make the change to https://github.com/dart-lang/pub_cache/blob/master/lib/pub_cache.dart#L112, but is there anything else I need to be aware of? My plan was to grab the value from `Platform.environment`, default it to `pub.dartlang.org` if no env variable exists.

**Comment by devoncarew** [comment]
@joeconwaystk, that plan sounds reasonable!

**Comment by devoncarew** [comment]
fixed by #35
