### ISSUE TITLE
Problems running my flutter app

### ISSUE THREAD

**Issue by WendahNyiawung** [dart-lang/pub_cache#39]
Good afternoon everyone please I am facing a problem running my flutter app here is the massage I always get 
Your application could not be compiled, because it’s dependencies could not be established.
Could not read “C:\flutter\.pub-cache\hosted\pub.dartlang.org\vector_math-2.0.8\lib\hash.dart” when determining Dart dependencies

**Comment by devoncarew** [comment]
Thanks for the report! I believe that message is unrelated to this package however.

**Comment by sigurdm** [comment]
@WendahNyiawung it sounds like a corrupted pub cache. Try deleting the entire C:\flutter.pub-cache\hosted\pub.dartlang.org\vector_math-2.0.8 folder, and run `flutter pub get` again.
