### ISSUE TITLE
searching for the pub folder

### ISSUE THREAD

**Issue by rdnobrega** [dart-lang/pub_cache#40]
Hi! Windows user here. dart 2.9.3

Installing aqueduct, i noticed that the method `PubCache.getSystemCacheLocation()` is searching for my pub folder by the 'APPDATA' key. However, in my system, Platform.Enviroment['APPDATA'] return the "\roaming" folder, whereas my pub cache is actually located at "\local" folder.

There is another key, Platform.Enviroment['LOCALAPPDATA'], the correctly returns the folder. There is no 'PUB_CACHE' key.

**Comment by rdnobrega** [comment]
As stated in other issue open in aqueduct, the reason that it may be broken for me is that i just download the dart sdk and register on path, not installed using chocolatey... maybe through choco you dont get this error.

**Comment by bsutton** [comment]
Looks like installing using chocolatey has the same issue. So it looks like pub-cache may simply be wrong.

**Comment by bsutton** [comment]
> By default, this directory is located under .pub-cache in your home directory (on Mac and Linux), or in %LOCALAPPDATA%\Pub\Cache (on Windows).

> (The precise location of the cache may vary depending on the Windows version.) 

I'm thinking that we should search both locations starting with the localappdata

**Comment by bsutton** [comment]
I've raised a PR that should fix this issue.

**Comment by devoncarew** [comment]
Fixed by https://github.com/google/pub_cache/pull/44 (and, `0.3.1` has been published with the fix).
